sudo: required
git:
  clone: false
language: python
python:
- '3.6'
before_install:
- curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
- sudo cpanm --notest DBI
- sudo cpanm --notest DBD::Pg
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker pull busybox
- docker pull flybase/proformatestdb
- docker pull flybase/harvdev-docker
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- git clone git@github.com:FlyBase/harvdev-proforma-setup.git
- cd harvdev-proforma-setup
- "./build_test_travis_perl.sh"
- pip3 install -r requirements.txt
- python3 ./test_scripts/run_tests.py
env:
  global:
  - secure: FuAsRSpV+Rjva39pLJEPOeRJCkpgiD+hQnTAtm2u2wTOzMz2mUTM/R8c1KgwkkID6qb9WHUEDhi0+LvXuOiPK+T5hcQX5OtQvXz+BoXtSW1V1zFcgPXWYEzTOeGGMXfvY7g7paSTBe9bP/xtj8x+VpA8tuqR+ehxTGEoTWgDo8RR/7Tz+FFXTWOBOrfH8bE+81mSVQX2mRGm+6a8T5i+M4hT7LRdF9wonIy5p4V8yC7yzo8xhwDF3khzw2JhAOpBHUpw2a6i/Ds7xRuyEpTjWc2U5Gs/FGr+QA+uJqRsJVt1XHKrpGCsYKbcpZ9uc0JJMr1PV4RN9SNifjrEwGqbHoXM9+wnlEg3/XXnUHS1LazcWkOC6RG2YsjDPszdNJKge7gQijk11XQ7pJnpXjFwOcvBZsBh0oM7JW+f0TEdLeRGjffDuue0plDD9JjBBdL4eCnDTlQJygvTTWjHtLsWpMsSY5xLcZe3ZOKIrP/OAdYNJl2Tm06VOg97EKvlJyOyNJH3RcjnxRuD3DhWRP/FFSFra3cM4ZmaruxoK9+rIKkXnZvWHoc0dMK3cm+t9oIsoGuFpvJpNAqFoP5dZIUXUG4hsw6weJ7NLhZTFTzdmMLTZacDJSfsm7s0jzNXImP8FvRpVjgT525DY7qwClKpSdPGsqp6/l9RV283CGbnBto=
  - secure: wrA7GD5mmEdT/A6tDAiLYlQOcsjO6fCuEtYxp0BZKT7H7WMFwqeKqpHxs5mGKwktVs0SzsgDHLz1aJZzmMKBu58WmKmzawhi/wZcrPqkTVuuaAQBZ6Zb66KCusSfXUStTX/CEkA+hCq1TyAvfTs4mYp61uQhg3khYeNI2p10cjqP2IOjDRNLcFt9d6z3nzQPIyuPNiuUlrGFXZPAbr5JISR87JDjKz9sdmeQaufEw9Py3t1AS/U9AfPcxEbLcgl+UMZV+/zaKP0cRLLdBeL95NiRJwZKArg2F9aJ/OdVHltsDKI42ccVM2XWYgn/KSdMUeQIHyVwkePdIX5zqZTWVLMRrrc36kola5uKYbbQhR36H20G/PUknQyHZo51vej6CF7erI3VMu+KlMdZwrRKDRGfXD7N5uywGesjgRSzviraQaZvO7kmmkxxt17CJcKMIzsRXueG/9NJyJuhM60JcwEFj9rm1uRPyOfyjV/kPNQVvJVZTmTPrQVK7uXdbCbYKA2yCFKnGtpvbkw5GHN7RpgcWJbE+2dXCNUn6m/WQidJ2SQhW5QYGY5q/e6NdCeU1fy7FISh8+uMq0bdSSqsjVbs8Jnmnfybm6siNLLZWZSpKBrVWGHPjdm8C3RjKwOONNS1VF8HtrLi2KbkTIskbynWdQXYqVLKvFscyDc96yE=
