sudo: required
git:
  clone: false
language: python
python:
- '3.6'
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
- sudo cpanm --notest DBI
- sudo cpanm --notest DBD::Pg
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker pull busybox
- docker pull flybase/proformatestdb
- docker pull flybase/harvdev-docker
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- git clone https://github.com/FlyBase/harvdev-proforma-setup.git
- cd harvdev-proforma-setup
- "./build_test_travis_perl.sh"
- pip3 install -r requirements.txt
- python3 ./test_scripts/run_tests.py
env:
  global:
  - secure: AD0FMjVGKU8EDztj1fzZFm1rLYleGYKYBY1/6BKve5cOiO2n/OnqjPwwRA8hH9JMM1RXcmPdKKCdD1/3Fnc3do6RsXsIjyu7vtiWONvWGNlfgCHUfKDei2BiVEv4thThXhqGbdoLmZeXdWBcZSAYyy/HJj/nNiuhjYxbs5CecWvodQ1kjn2fcNkD88Tdqsxb1eaed/R8sH8CQUnEfz5odBfw/b8LooCy+oXzW7qCM4ZkKr63KuXGmDHearadl7Se90mJMXMrOiMc8ZI7TfXPwqBFbTLB3vtATb4L+clrzCn1E845ZRjc1bIEthZtntTq4F21b5VyIKvVygW7jn04BJn+fS0KRIpE3Ia089KY9aW2Sao6vwZLWWcnm5fjaoMOrsGrW5IXmpwh240E6u+GHrYS/31KuBfk/z0UOwwbTuvZmQ647zQna255I56rV7Owhv9umM5a4S0jhpXGezZ9igSS/SZr7/pD1OTM5GvdfnFaGbk8CzF5TLJJE6JkJPey+oLHsBDcDpLeQ/atGBPIHPa+3853xpO7f07HLdd8m+YTH12ZZwFvCb3QGyqubkC+iUDpqW6Ll3h5Fv0/c7HXx9xJwSEkKk+XN+eUUD96vtgJpKHga68fk+umfVdUSOXqFK79IQU29ujTPLmcOJDDXmM/Hsm7lAIA58UXQOzUUF0=
  - secure: eF19TKUmMQl4C+oIn19JItdYtUJZJsFOTYTn5Eo9IJZoTU8b8hoHwQ1oKYkJtFSB68yoRlgEXt+KPor0ru2rKHZ6Gu+FYpUI1gReK1NtQjYTI9meWuQw3DuAok7Za5Kse0QNF6HcmtjI0g0KbqEzg3FGrR+49Y7+Wd84R+G1X9OFQ07KAueQiHpUsqJmYyPgGlaDSDM98rYmFbewGPvnVkbMjRVa+EoM02Y6EBXUkDaITm+HxpVcFJM6vYuqZix3lkaeOSjfb5OWNdPv5gAqV8JcNnFNaDtMYM3j+Pq++DiFnHBAKxpmrMYHDYwt7QzNUkOe8dGZGDK+wIEOLsY9SeGhyrKVFZc1q2KVBP9D+uL4MjniNsVRieAgpwITMj6iRTl6RHfuWxOX8ikelrRL0cnOMDZxJNSQFGqMMpCAoY6EhaTXp2zr58y7Zpf5NMj0QAGUdL67uU7QBy8PSb7h6IiKvzYsh6q5Qx/xIHoir9dZJIeOcHPdfNN1kgR3/k0dmPH0NVJ5Kl6az+3qmHG+SVnLkKVJ6kT8Cekcg3ibePc2NE7nP2kQsgMuabtrrkDuDrF583jzvCO6UInm1lCQ44XPYR4ORlb2zRnmcE66PErjFkjihRz7YuoAx92HkHVhuzeUpDcySsjuio1cAL/K/R2oa7TmkyGilsh25A8DG3A=
  - secure: jGqhzFX4G68FeSgClOQz5z+50SMuqxX89hOdwIfXnZqwZH4FbwrlxSiKKhd79E81f+2whqvXpS+yNXbXc2NSC1is5m8Llvjdzr3hbO6ecvwFdTmhOJrJ2Do2gJpT9LNJIAqYfk10Vmzy0fOOjWhr/GDODoHFOq03LlxtpCg+PeMaChIw46mueqHuyZxdWz9svPLGHbZMPMhO3IzHhKDU7dv3ASf6cKe4N8epTWt3AXojb2aFU1RAKzUWBxDbBAXsIUayZ2f0F/7NaS2RS4wVNbuFX7FEYMANJfy+OnqEhyaQv9hoGpoWu8jnVx5YxM+vp+/+iBklsatHdhtpXLgUAyRQaLCDKuSA9c1DgvvY/zuZrmOxWYT/xsnlOyFHVYYQRPkPvbUpkZEwqKErxnhmjEXGAU1KPxNolmIcAmk/HI+Kwh4v/vXf9zGDGyAR53PLfzOE9hh1zGUILsOUnBt8v8VDki7bp0HXXvGQKylelDenR/IhAYV08xk3YFt5I1I8faT5g3QA1KpxtXJGUhoxXoDNPEbhP6mwhcg3MouJTsauQrHv5bPilTKRNhbQpNd8TaI86A46nHBT+mRUKXZTuQ5WsS6TcO5pBOJkbzTS+kl/MREP4bthOaeu+AOx1LoLNN8i1bKXEOlXs+yZ50UNZFqfFNDOCNFq6KRsNv0JXNU=
