version: "3.2"

services:
  perl_proforma_parser:
    build: .
    image: flybase/harvdev-perl-proforma-parser:latest
    volumes:
      - type: bind
        source: ../proforma
        target: /proforma
    network_mode: host

networks:
  default:
    external:
      name: proforma_net

